### ISSUE TITLE
message_flow.md file missing from source

### ISSUE THREAD

**Issue by weezqyd** [gernest/mpesa-dev-api#6]
Error while building the documentation the `message_flow.md` file is missing,  either remove the key from `mkdocs.yml` or remove it from the `.gitignore` list 

``` yml
pages:
#....other pages
- Message Flow:     message_flow.md # remove this or ad the markdown_file
#...other pages
```
